name: floodguard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geocoding: ^2.0.5
  connectivity_plus: ^4.0.0
  flare_flutter: ^3.0.0
  font_awesome_flutter: ^10.2.1
  intl: ^0.19.0 # For date and time formatting
  permission_handler: ^10.2.0 
  flutter_spinkit: ^5.1.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/day.jpg          # Flare animation for day
    - assets/night.jpg      # Flare animation for night
    - assets/cloudy.jpg         
    - assets/rainfall.jpg         
    - assets/snow.jpg   
    - assets/sunset.jpg
